#!/bin/bash

apt-get -y install zsh
apt-get -y install openssh-server
apt-get -y install vim
apt-get -y install screen
apt-get -y install git
apt-get -y install xsel
apt-get -y install rdesktop
apt-get -y install xrdp
