#!/bin/zsh

listPackages() {
    echo $NINJAS_PATH/default
    find -L $HOME/.ninjas/ -maxdepth 1 -mindepth 1 -type d 2> /dev/null | sort
    local extra=""

    for extra in $EXTRA_PACKAGES; do
        echo $extra
    done
}

parseExtraPackages() {
    while [[ "$1" != "" ]]; do
        if [[ "$1" == "--ninja" ]]; then
            shift

            EXTRA_PACKAGES+="$1"
        fi

        shift
    done
}

listVimPaths() {
    packages=($(listPackages))

    for package in $packages; do
        if [[ -e $package/vimpaths ]]; then
            cat $package/vimpaths
        fi
    done
}

relink() {
    if [[ ( -L $2 ) || ( ! ( -e $2 ) ) ]]; then
        echo "Linking $2 to point to $1"
        ln -sfn $1 $2
    else
        echo "File $2 already present. Please remove it first"
        exit 1
    fi
}

# Usage:
#     replaceIfDifferent DST SRC
#     If the files at $DST and $SRC have different md5sums then replace $DST with $SRC (via move).
#     If they are the same MD5 then just delete $SRC.
replaceIfDifferent() {
    if [[ "$1" == "" || "$2" == "" ]]; then
        return
    elif [[ ! -e "$1" && -e "$2" ]]; then
        # Nothing at the $DST spot so just move it over.
        mv "$2" "$1"
        return
    elif [[ ! -e "$2" ]]; then
        # Nothing at the $SRC spot, nothing to do.
        return
    else
        # Subshell to avoid polluting the function table.
        (
            # Different OSes have different commands for md5 sum.
            innerMd5() {
                which md5 > /dev/null && ( md5 < "$1" ; return)
                which md5sum > /dev/null && ( md5sum "$1" ; return)
            }

            if [[ "$(innerMd5 "$1")" == "$(innerMd5 "$2")" ]]; then
                rm "$2"
            else
                mv $2 $1
            fi
        )
    fi
}

createRcHeader() {
    echo "# DO NOT EDIT. THIS FILE IS AUTOGENERATED."
}

createGitConfigHeader() {
    createRcHeader
    echo "[include]"
}
