#!/bin/zsh

pwd > ~/.ninjas

relink()
{
    if [[ ( -L $2 ) || ( ! ( -e $2 ) ) ]]; then
        echo "Linking $2 to point to $1"
        ln -s -f $1 $2
    else
        echo "File $2 already present. Please remove it first"
        exit 1
    fi
}

# deploying vimrc
relink $(cat ~/.ninjas)/.vimrc ~/.vimrc

# deploying zsh stuff
relink $(cat ~/.ninjas)/.zshrc ~/.zshrc
relink $(cat ~/.ninjas)/.zshenv ~/.zshenv

# deploying screenrc
relink $(cat ~/.ninjas)/.screenrc ~/.screenrc
