#!/bin/zsh

NINJAS_PATH=$(realpath $(dirname $0))

source $NINJAS_PATH/helpers.zsh

if [[ -f ~/.ninjas ]]; then
    echo "Removing legacy install."
    rm ~/.ninjas
fi

mkdir -p ~/.ninjas
mkdir -p ~/.vim/swp

echo $NINJAS_PATH > ~/.ninjas/.path

# deploying vimrc
relink $NINJAS_PATH/.vimrc ~/.vimrc

# deploying zsh stuff
relink $NINJAS_PATH/.zshrc ~/.zshrc
relink $NINJAS_PATH/.zshenv ~/.zshenv

# deploying screenrc
relink $NINJAS_PATH/.screenrc ~/.screenrc

# deploying .git config
relink $NINJAS_PATH/.gitconfig ~/.gitconfig

# deploying hgrc
relink $NINJAS_PATH/.hgrc ~/.hgrc
