#!/bin/zsh

source helpers.zsh

if [[ -f ~/.ninjas ]]; then
    echo "Removing legacy install."
    rm ~/.ninjas
fi

mkdir -p ~/.ninjas

pwd > ~/.ninjas/.path

# deploying vimrc
relink $PWD/.vimrc ~/.vimrc

# deploying zsh stuff
relink $PWD/.zshrc ~/.zshrc
relink $PWD/.zshenv ~/.zshenv

# deploying screenrc
relink $PWD/.screenrc ~/.screenrc

# deploying .git config
relink $PWD/.gitconfig ~/.gitconfig

# deploying hgrc
relink $PWD/.hgrc ~/.hgrc
