unsetopt beep
setopt inc_append_history

bindkey -e
bindkey ^x accept-search
bindkey ';5D' backward-word
bindkey ';5C' forward-word

alias jerbs=jobs
alias exeunt=exit
alias dirs=dirs\ -p

set -o emacs

() {
    local platZsh;platZsh="$(uname).zsh"
    (which $platZsh > /dev/null 2> /dev/null) && source $platZsh
}

# Update the prompt string to include the "prompt_header"
# and set the screen's title if we're inside of a screen.
update_dir() {
    local PROMPT_HEADER;PROMPT_HEADER="$(prompt_header.py)"
    PS1=" ## $PROMPT_HEADER%c $ "
    if [[ "$STY" != "" ]]; then
        stitle.sh
    fi
}

chpwd() {
    # Update the prompt and screen title whenever we change pwd.
    update_dir
}

zshaddhistory() {
    echo -n $1 >> ~/.zshpermanenthistory
}

pvim() {
    vim $@ -c "setlocal buftype=nofile" -c "setlocal bufhidden=hide" -c "setlocal noswapfile" -
}

svim() {
    vim $@ -c "setlocal buftype=nofile" -c "setlocal bufhidden=hide" -c "setlocal noswapfile"
}

() {
    if [[ "$SCREEN_CMD" == "" ]]; then
        local SCREEN_CMD;SCREEN_CMD=screen
    fi

    if [[ $(screen -ls | grep -i ${USER}_scr | wc -l) -eq 0 ]]; then
        $SCREEN_CMD -d -m -S ${USER}_scr
    fi
}

# Update the prompt and screen title at startup.
update_dir

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
