#!/bin/zsh -e

git log -M -C --name-only --format='format:' "$@" | sort | grep -v '^$' | uniq -c | sort -n | awk 'BEGIN {print "Count;File"} {printf("%s", $1); print ";" substr($0, index($0,$2))}' | column -t -s \;
